env:
  node: true
  commonjs: true
  mocha: true
extends: 'eslint:recommended'
rules:
  accessor-pairs: error
  array-bracket-spacing:
    - error
    - never
  array-callback-return: error
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  block-scoped-var: error
  block-spacing: error
  brace-style:
    - error
    - 1tbs
  callback-return: error
  camelcase:
     - error
     - properties: never
  capitalized-comments: 'off'
  class-methods-use-this: error
  comma-dangle: 'off'
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity: error
  computed-property-spacing:
    - error
    - never
  consistent-return: error
  consistent-this:
    - error
    - self
  curly: error
  default-case: error
  dot-location: error
  dot-notation: error
  eol-last: error
  eqeqeq:
    - error
    - always
    - null: ignore
  func-call-spacing: error
  func-name-matching: error
  func-names:
    - error
    - never
  func-style:
    - error
    - declaration
  generator-star-spacing: error
  global-require: error
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-length: 'off'
  id-match: error
  indent:
    - error
    - 2
  init-declarations: 'off'
  jsx-quotes: error
  key-spacing: 'off'
  keyword-spacing:
    - error
    - after: true
      before: true
  line-comment-position: 'off'
  linebreak-style:
    - error
    - unix
  lines-around-comment: error
  lines-around-directive: error
  max-depth: error
  max-len: 'off'
  max-lines: 'off'
  max-nested-callbacks: error
  max-params: 'off'
  max-statements: 'off'
  max-statements-per-line: error
  multiline-ternary:
    - error
    - never
  new-cap: error
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: 'off'
  no-alert: error
  no-array-constructor: error
  no-caller: error
  no-compare-neg-zero: error
  no-confusing-arrow: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: 'off'
  no-eq-null: 'off'
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: 'off'
  no-inner-declarations:
    - error
    - functions
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers: 'off'
  no-mixed-operators: 'off'
  no-mixed-requires: error
  no-multi-assign: 'off'
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines: error
  no-native-reassign: error
  no-negated-condition: 'off'
  no-negated-in-lhs: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: 'off'
  no-path-concat: error
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: 'off'
  no-shadow-restricted-names: error
  no-spaced-func: error
  no-sync: error
  no-tabs: error
  no-template-curly-in-string: error
  no-ternary: 'off'
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-undefined: 'off'
  no-underscore-dangle: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unused-expressions: error
  no-use-before-define: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-escape: error
  no-useless-rename: error
  no-useless-return: error
  no-var: 'off'
  no-void: error
  no-warning-comments: error
  no-whitespace-before-property: error
  no-with: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  object-curly-spacing: error
  object-property-newline: error
  object-shorthand: 'off'
  one-var: 'off'
  one-var-declaration-per-line:
    - error
    - initializations
  operator-assignment:
    - error
    - never
  operator-linebreak: error
  padded-blocks: 'off'
  prefer-arrow-callback: 'off'
  prefer-const: error
  prefer-numeric-literals: error
  prefer-promise-reject-errors: error
  prefer-reflect: 'off'
  prefer-rest-params: 'off'
  prefer-spread: error
  prefer-template: 'off'
  quote-props: 'off'
  quotes: 'off'
  radix: error
  require-await: error
  require-jsdoc: 'off'
  rest-spread-spacing: error
  semi: 'error'
  semi-spacing: error
  sort-imports: error
  sort-keys: 'off'
  sort-vars: 'off'
  space-before-blocks: error
  space-before-function-paren: error
  space-in-parens: 'off'
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - always
  strict:
    - error
    - safe
  symbol-description: error
  template-curly-spacing: error
  template-tag-spacing: error
  unicode-bom:
    - error
    - never
  valid-jsdoc: error
  vars-on-top: 'off'
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
  yoda:
    - error
    - never
